sonar.projectKey=ifs24056-pabwe2026-reactjs
sonar.projectName=ifs24056-pabwe2026-reactjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,src/main.jsx,src/setupTests.js,src/test-utils.jsx,**/*.test.js,**/*.test.jsx
sonar.coverage.exclusions=src/App.jsx,src/App.css,src/index.css,src/features/**,src/helpers/**,src/hooks/**,src/assets/**,src/main.jsx,src/setupTests.js